version: "3.7"
services:
  app:
    build:
      args:
        user: jocker
        uid: 1000
      context: ./_docker
      dockerfile: app_alpine.dockerfile
    image: englcards
    ports:
      - 5173:5173
    container_name: englcards-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - englcards



  nginx:
    image: nginx:alpine
    container_name: englcards-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./_docker/nginx:/etc/nginx/conf.d/
    networks:
      - englcards

  db:
    image: postgres:16-alpine
    container_name: englcards-db
    ports:
      - 5444:5432
    restart: always
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: langcards
      POSTGRES_DB: langcards_db
    networks:
      - englcards

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - englcards

networks:
  englcards:
    driver: bridge
